/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "App": string|undefined
  "App-header": string|undefined
  "App-link": string|undefined
  "App-logo": string|undefined
}
