/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
export type CssIdentifiersMap = {
  "button": string|undefined
  "button__icon": string|undefined
  "button__label": string|undefined
}

declare const identifiersMap: CssIdentifiersMap

export default identifiersMap
