/** Auto generated by [postcss-plugin-d-ts](https://github.com/askirmas/postcss-plugin-d-ts) */
export type CssIdentifiersMap = {
  "scss_module": string|undefined
}

declare const identifiersMap: CssIdentifiersMap

export default identifiersMap
