/** Auto generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
export type CssIdentifiersMap = {
  "some_scss": string|undefined
}

declare const identifiersMap: CssIdentifiersMap

export default identifiersMap
