/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
export type CssIdentifiersMap = {
  "dialog__close": string|undefined
}

declare const identifiersMap: CssIdentifiersMap

export default identifiersMap
