/** Auto generated by [postcss-plugin-d-ts](https://github.com/askirmas/postcss-plugin-d-ts) */
export type CssIdentifiersMap = {
  "class": string|undefined
  "class2": string|undefined
  "classname": string|undefined
  "id": string|undefined
  "my-id": string|undefined
}

declare const identifiersMap: CssIdentifiersMap

export default identifiersMap
